name: CI

on:
  pull_request:
  push:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Lint chatmaild
        working-directory: chatmaild
        run: pipx run tox
      - name: Lint deploy-chatmail
        working-directory: deploy-chatmail
        run: pipx run tox
